language: node_js
node_js: stable

before_install:
 - npm install
script: 
 - npm run build
 - npm run cov

before_deploy:
  - export BODY=$(git log --pretty=format:"%s" $TRAVIS_COMMIT_RANGE)

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: "test"
    body: ${BODY}
    on:
      tags: true
