language: node_js
node_js:
 - 'node'
 - '8'
 - '7'
before_install:
 - npm install
script: 
 - npm run build
after_script:
 - npm run cov

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: $TRAVIS_TAG
    body: git log --pretty=format:"%s" $TRAVIS_COMMIT_RANGE
    on:
      all_branches: true
      