language: node_js
node_js: stable

before_install:
 - npm install
script: 
 - npm run build
after_script:
 - npm run cov

before_deploy:
  - export BODY=$(git log --pretty=format:"%s" $TRAVIS_COMMIT_RANGE)
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: ${TRAVIS_TAG}
    body: ${BODY}
    on:
      all_branches: true
